# Site settings
baseurl:
title: Ken Mayer
subtitle: Mutterings of the Global Village Idiot
description: >
  Ramblings about technology, traveling, sailing, family, entrepeneurship.
  Mostly ramblings.
author: Ken Mayer
email: ken@bitwrangler.com
timezone: America/Los_Angeles
url: "http://blog.bitwrangler.com" # the base hostname & protocol for your site

simple_search: http://google.com/search

markdown: kramdown
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  input: GFM

excerpt_separator: "\n\n"  # you can specify your own separator, of course.
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - TODO.txt
  - LICENSE
  - UploadToGithub.Rakefile
  - tufte.zip